### ISSUE TITLE
trying to build this samething in react.

### ISSUE THREAD

**Issue by abue-ammar** [BraydenTW/obsidian#2]
hey i am trying to build this same thing with react. but everything is working fine but my dark mode is not working properly. when dark mode is enabled and i refresh the page the screen flashes white. how do i fix this? i am using next-themes package in my project.
if you could help me fixing this dark mode flashing issue. here is my repo https://github.com/abdarker/abdarker.github.io and it's live in here you can check the flashing issue when it is in dark mode and click refresh page https://abdarker.github.io

**Comment by BraydenTW** [comment]
Hey @abdarker, I do not see the same issue happening on the current https://obsidian-portfolio.vercel.app website, but it does occur on yours.

My guess is that it might be because it is set to the light theme on your side initially, but then it overrides it just milliseconds after when the system default of dark them is set.

Have you changed anything from the original code of this repo that might make it do that?

**Comment by abue-ammar** [comment]
it took a while. but i finally managed to fixed the issue! with nextjs it was easier but in regular react fixing that flashing issue was quite tricky. but it's fixed.
